Sprint 1
Tengy83/middle.messenger.praktikum.yandex pull request #1
Opened 2021-07-08 18:11 UTC by Tengy83

2021-07-09 10:57 UTC, nickchamel requested changes
Привет! Я не смог посмотреть работу, добавь пожалуйста ссылку на нетлифай. По коду оставил тебе комментарии, ознакомься пожалуйста, работу пока возвращаю

2021-07-09 10:57 UTC, nickchamel commented on README.md
> -### Ветка, в которой делаете задания спринта, должна называться sprint_i, где i - номер спринта. Не переименовывайте её.
в Readme нет ссылки на проект на netlify. Я должен посмотреть результат работы

2021-07-09 10:57 UTC, nickchamel commented on dist/img/bigLogoBg.svg
> +<svg width="192" height="192" viewBox="0 0 192 192" fill="none" xmlns="http://www.w3.org/2000/svg">
папка dist должна быть в `.gitignore`

2021-07-09 10:57 UTC, nickchamel commented on index.js
> +import 'regenerator-runtime/runtime';
зачем здесь полифилы? Я по коду не заметил, чтобы ты что-то использовал из них. Если так, то это лишнее и можно удалить из кода, далее будет тайпскрипт, там все равно это не нужно будет

2021-07-09 10:57 UTC, nickchamel commented on index.js
> +
index.js должен быть в src/
index.html можно держать в корне, а лучше в static

2021-07-09 10:57 UTC, nickchamel commented on index.js
> +};
лучше вынести импорты наверх, а здесь прописать переменные

2021-07-09 10:57 UTC, nickchamel commented on index.js
> +const root = document.querySelector('#root');
у тебя вроде в константах был этот селектор, тогда было бы неплохо ее тут использовать

2021-07-09 10:57 UTC, nickchamel commented on index.js
> +  }
и тут не нужно будет усложнять код когда импорты вынесешь наверх
```
import { createError404Page } from './src/pages/error404';
...
const createCurrentPage = pages[name] || createError404Page;
root.innerHtml = createCurrentPage();
```

2021-07-09 10:57 UTC, nickchamel commented on index.js
> +const errorUrl = window.location.pathname.length;
Непонятно каким это образом длина pathname является errorUrl)
Старайся правильно называть имена переменных. Если это длина то так и назови pathnameLength

2021-07-09 10:57 UTC, nickchamel commented on index.js
> +}
Тебе нужно просто взять pathname и отрендерить его `renderPage(window.location.pathname)`
А там уже будет отрендерена она из твоих страниц либо 404 (смотри комментарий через 1 выше)

2021-07-09 10:57 UTC, nickchamel commented on index.js
> +    link.addEventListener('click', pageRenderListaner);
опечатка правильно будет ListEner

2021-07-09 10:57 UTC, nickchamel commented on index.js
> +    }
А зачем тебе здесь `else`? Я так понимаю ты вешаешь обработчик на твои ссылки с атрибутом `data-page`, значит если кликнули именно по такой ссылке то нужно сделать рендер, а иначе ничего делать не нужно.
Здесь это все лишнее. то есть нужно сделать проверку на e.target.attributes - нужно чтобы там был `data-page`. Если есть то делаем рендер, если нет то ничего не делаем

2021-07-09 10:57 UTC, nickchamel commented on src/modules/authorization/authorization.tmpl.js
> +  </form>
отступы

2021-07-09 10:57 UTC, nickchamel commented on src/modules/chatStub/chatStub.tmpl.js
> +  </div>
здесь тоже (пробегись по всем подобных местам, пожалуйста)

2021-07-09 10:57 UTC, nickchamel commented on src/modules/authorization/authorization.tmpl.js
> +    <{{ dom }} class="{{ className }}">
нет нужны хранить tag элемента в константах, он должен быть описан здесь. Так сразу понятно что и как и не надо никуда идти смотреть что же тут за элемент будет. И ты ведь не будешь их динамически менять правильно?
То же самое относится к именам классов, они должны быть в шаблонах а не в переменных, иначе ты связываешь слои приложения, и при изменении одного слоя (шаблонов) это отражается на других слоях (все класснеймы и тэги стоит перенести в темплейты) здесь можешь оставить `name` `type` и т.п. В других шаблонов тоже самое

2021-07-09 10:57 UTC, nickchamel commented on src/pages/chats.js
> +  return template.trim() + contentWrapper(templateWrapper.trim());
А зачем это все? Сплошь усложения, сложно читать, сложно поддерживать
Ты можешь написать просто 
```
const templateWrapper = createUsersList() + createChatStub();
const template = createHeader()
return template.trim() + contentWrapper(templateWrapper.trim());
```
и все.
Только все равно сложно читать. Я вот например не понимаю почему в темплейте у тебя получается хедер, а во враппере юзер лист и еще что-то там.
Старайся как-то называть переменные чтобы это было легко читать. То есть враппер это же обертка. По идее это может быть `content` или `mainContent` а херед `header`

2021-07-09 10:57 UTC, nickchamel commented on src/pages/chats.js
> +  return tmpl.compile(state.store[stateModuleName]);
мы должны придерживаться модульной структуры, поэтому эти данные лучше разбить по своим модулям 
(state) и разложить по папкам своих модулей

2021-07-09 10:57 UTC, nickchamel commented on src/pages/error404.js
> +  return template.trim();
Дальше то же самое, советую избавиться от этой логики (объект + Object.keys) у тебя все равно страницы будут всегда выводить какой-то конкретный результат.
Либо как минимум ты мог бы вынести это и returnTmpl в utils потому что дальше у тебя это везде повторяется

2021-07-09 10:57 UTC, nickchamel commented on utils/utils.js
> +}
отступы
и я так понимаю это твой лэйаут. Если так то ты можешь создать папку layouts и положить его туда. Все таки utils немного не про это...

2021-07-11 10:20 UTC, Tengy83 commented on README.md
> -### Ветка, в которой делаете задания спринта, должна называться sprint_i, где i - номер спринта. Не переименовывайте её.
На данный момент ссылки нет, фэйлдится проэкт. На локалке запускается без проблем

2021-07-12 09:40 UTC, Tengy83 commented on README.md
> -### Ветка, в которой делаете задания спринта, должна называться sprint_i, где i - номер спринта. Не переименовывайте её.
Ссылка добавлена

2021-07-12 11:22 UTC, nickchamel commented on index.js
> +  }
не исправлено

2021-07-12 11:22 UTC, nickchamel commented on index.js
> +const errorUrl = window.location.pathname.length;
не исправлено

2021-07-12 11:23 UTC, nickchamel commented on index.js
> +}
не исправлено, если тебе что-то непонятно - можешь задать вопрос

2021-07-12 11:23 UTC, nickchamel commented on index.js
> +    link.addEventListener('click', pageRenderListaner);
тоже можно бы исправить

2021-07-12 11:23 UTC, nickchamel commented on index.js
> +    }
не исправлено

2021-07-12 11:24 UTC, nickchamel commented on src/modules/chatStub/chatStub.tmpl.js
> +  </div>
не исправлено

2021-07-12 11:25 UTC, nickchamel commented on src/modules/authorization/authorization.tmpl.js
> +  </form>
не исправлено

2021-07-12 11:25 UTC, nickchamel commented on src/modules/chatStub/chatStub.tmpl.js
> +  </div>
в других шаблонах тоже не поправлено,

2021-07-12 11:29 UTC, nickchamel requested changes
Привет, некоторые комментарии проигнорированы, пробегись пожалуйста по ним, и проверь все шаблоны - постарайся привести их к одному виду.
Насчет ссылки на нетлифай - она нерабочая
Без проекта залитого на нетлифай, работа не может принята, к сожалению.
Работу пока возвращаю.

2021-07-12 12:26 UTC, Tengy83 commented on index.js
> +    }
Код упростил, но не убрал, т.к. если внутри линка есть img или span(пример лого в хедере), таргетом будут именно они и доступа к data-page не будет

2021-07-12 15:08 UTC, nickchamel requested changes
Привет. Оставил комментарии, необходимо доработать. Плюс так же по заданию 1ого спринта нужно чтобы были сверстаны все страницы, кроме чатов (заглушка), то есть должна еще быть страница профиля, его редактирования, а так же смены пароля

2021-07-12 15:08 UTC, nickchamel commented on src/index.js
>    }
Если есть вложенные элементы, то ты можешь использовать `currentTarget`
```
function pageRenderListener(e) {
  e.preventDefault();
  const pageName = e.currentTarget.getAttribute('data-page'));
  renderPage(pageName);
}
```
https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget

2021-07-12 15:08 UTC, nickchamel commented on src/modules/form/form.tmpl.js
> +}
Файлы с расширением `.tmpl.js` должны содержать только шаблон, 1 файл - 1 шаблон (либо функция возвращающая шаблон)
У тебя здесь несколько шаблонов
К примеру 
`<form action="{{form.action}}" method="{{form.method}}" class="{{form.className}}">${inputs}${buttons}</form>` это общий щаблон формы - он здесь должен быть 1 единственный.
Затем у тебя здесь есть `<input type="{{form.inputs.${inputName}.type}}" name="{{form.inputs.${inputName}.name}}" class="{{form.inputs.${inputName}.className}}" placeholder="{{form.inputs.${inputName}.placeholder}}" />` это совершенно другой шаблон другого модуля (инпут). Он должен лежать в своем файле с расширением `.tmpl.js` своего модуля. Если инпут у тебя где-то используется кроме формы, то можешь создать для него папку в том же месте где у тебя все компоненты хранятся, а если инпут используется только  в компоненте формы - то можешь создать для него папку в `src/modules/form/components/input`, например. И в этой папке все должно быть как и в любом другом модуле - то есть js-файл, файл с шаблоном, файл со стилями этого модуля.
А само создание компонента должно быть не в `.tmpl.js` а в js-файле того модуля, в котором этот компонент используется. То есть например если у тебя инпут в форме, то в js-файле модуля формы, ты импортишь js-файл модуля инпута (в нем ты создаешь инпут из шаблона инпута), так же тут импортится шаблон формы, потом он рендерится и вместе с контекстом ты ему передаешь созданный инпут.
И так далее с каждым компонентом. Нужно все разнести по своим "полочкам", сейчас все очень сложно и запутано. Надеюсь доступно объяснил, если что спрашивай

2021-07-13 11:07 UTC, nickchamel requested changes
Привет, еще нужно доработать, работу пока вернул

2021-07-13 11:07 UTC, nickchamel commented on src/index.js
> +  change_password,
Старайся писать в одном стиле, пиши по максимум в одном кейсе. Стандарт javascripta - camelCase

2021-07-13 11:07 UTC, nickchamel commented on src/modules/button/button.tmpl.js
> +  return `${hr}<{{form.buttons.${buttonName}.tag}} ${href} class="{{form.buttons.${buttonName}.className}}" ${dataPage}>{{form.buttons.${buttonName}.title}}</{{form.buttons.${buttonName}.tag}}>`;
Уже вроде писал об этом, не стоит передавать тэги и имена классов так, пиши их статично по максимуму
И у тебя в шаблонах есть `{{}}`, которые компилит Templator, а есть `${}`, которые ты компилишь как ES6-строки, неплохо бы оставить только одну компиляцию - темплейтора, а у тебя происходит 2 стадии компиляции с 2умя разными контекстами. Все это сильно усложняет код уже сейчас, а дальше будет только хуже в этом плане

2021-07-13 11:07 UTC, nickchamel commented on src/modules/changePassword/changePassword.tmpl.js
> +    ${createForm(state.form)}
Тоже уже писал, в шаблоне только шаблон, а создание компонентов шаблона - в js-файлах, не В `.tmpl.js`
В остальных файлах так же

2021-07-13 11:07 UTC, nickchamel commented on src/modules/form/components/input/input.tmpl.js
> +  return `<input type="{{form.inputs.${inputName}.type}}" name="{{form.inputs.${inputName}.name}}" class="{{form.inputs.${inputName}.className}}" ${placeholder} ${value} />`;
Здесь тоже className лучше сделать статичным, если есть необходимость динаически влиять на класс, то в контексте лучше прокинуть некое значение, которое потом можно добавить к имени класса, например 
`class="input input_{{type}} input-{{valid}}"`
В остальны местах так же

2021-07-13 11:07 UTC, nickchamel commented on src/modules/user/state.js
> +        dataPage: 'edit_user',
здесь только title можно оставить и dataPage, остальное статика, + придерживайся camelCase

2021-07-13 11:07 UTC, nickchamel commented on src/modules/user/state.js
> +        dataPage: 'change_password',
здесь тоже title и dataPage

2021-07-13 11:07 UTC, nickchamel commented on src/modules/user/state.js
> +        hr: true,
Логика по hr здесь лишняя, там куда ты будешь вставлять этот компонент, там ты и используешь/не используешь hr в шаблоне.
То есть например кнопка у тебя исп. в шаблоне А и в шаблоне Б - в шаблоне А есть  hr, после которого идет кнопка, а в шаблоне Б сразу идет кнопка без hr.
А так ты усложняешь композицию компонентов

2021-07-13 11:07 UTC, nickchamel commented on src/modules/user/user.tmpl.js
> +  return buttons;
уже писал, вся логика по созданию - в js, а не в .tmpl.js
Логи можно убрать

2021-07-13 11:50 UTC, Tengy83 commented on src/index.js
> +  change_password,
Это названия страниц, которые могут быть выведены в url, а там camelCase не работает. Поэтому и выбрал такой формат

2021-07-13 12:08 UTC, Tengy83 commented on src/modules/button/button.tmpl.js
> +  return `${hr}<{{form.buttons.${buttonName}.tag}} ${href} class="{{form.buttons.${buttonName}.className}}" ${dataPage}>{{form.buttons.${buttonName}.title}}</{{form.buttons.${buttonName}.tag}}>`;
Усложнения связаны с универсальностью модуля, кнопка может быть как тэгом A, так и тегом BUTTON, использоваться как в форме, так и отдельно. Про {{}} и ${}, опять же связано с универсальностью, нельзя заранее знать нужен ли атрибут или нет. Поэтому в зависимости от контекста шаблон и собирается. Контекст один и зависит от того модуля где применяется эта кнопка. Единственный вариант все это исключить, это писать форму целиком, но тут уже нет никакой модульности и универсальности. Если в дальнейшем это все будет сильно усложнять код, то тогда просто избавлюсь от модуля кнопки. Я не уверен что создание кучи шаблонов одной кнопки, зато без использования ${} - это упрощение.

2021-07-13 12:47 UTC, nickchamel commented on src/modules/button/button.tmpl.js
> +  return `${hr}<{{form.buttons.${buttonName}.tag}} ${href} class="{{form.buttons.${buttonName}.className}}" ${dataPage}>{{form.buttons.${buttonName}.title}}</{{form.buttons.${buttonName}.tag}}>`;
Вот ты не уверен, а я уверен
```

export function createButton(buttonState, buttonName) {
  const hr = buttonState['hr'] ? `<hr />` : '';
  const href = buttonState['href']
    ? `href="{{form.buttons.${buttonName}.link}}"`
    : '';
  const dataPage = buttonState['dataPage']
    ? `data-page="{{form.buttons.${buttonName}.dataPage}}"`
    : '';

  return `${hr}<{{form.buttons.${buttonName}.tag}} ${href} class="{{form.buttons.${buttonName}.className}}" ${dataPage}>{{form.buttons.${buttonName}.title}}</{{form.buttons.${buttonName}.tag}}>`;
}
```
```
export const Button = `
  <button type="button" class="button button_{{type}}">{{text}}</button>
`;

export const Link = `
  <a href="#" class="link link_{{type}}" data-page="{{page}}">{{text}}</a>
`;
```
Если для тебя все-равно это не очевидно, можешь отправлять работу - я приму как есть. Я сделал все, что было в моих силах, спорить я не намерен

2021-07-14 18:27 UTC, Tengy83 commented on src/modules/form/components/input/input.tmpl.js
> +  return `<input type="{{form.inputs.${inputName}.type}}" name="{{form.inputs.${inputName}.name}}" class="{{form.inputs.${inputName}.className}}" ${placeholder} ${value} />`;
Если честно, то не понимаю зачем писать жестко классы, ели можно динамически из стэйта, это может ускорить в дальнейшем при необходимости переименование классов. Жесткая привязка классов, как мне кажется нужна  только  там, где DOM вызывается в скриптах, дабы эти скрипты не сломались. У меня пока такого взаимодействия нет. Как появится тогда и добавлю где необходимо

2021-07-14 18:29 UTC, Tengy83 commented on src/modules/user/state.js
> +        dataPage: 'edit_user',
dataPage не статика, в зависимости где вызывается модуль кнопки он может быть или нет. Также camelCase тут не работает, т.к. это url страниц

2021-07-15 10:45 UTC, merged