Sprint 2
Tengy83/middle.messenger.praktikum.yandex pull request #2
Opened 2021-08-01 17:32 UTC by Tengy83

2021-08-02 19:19 UTC, avdoshenkov requested changes
Хорошая работа! 

Несколько моментов поправить и будет отлично. Ещё вот какая рекомендация есть: выводить сообщения об ошибке валидации под полем ввода. Потому что, например, вот в таком виде не понятно, что от меня хочет форма в случае с телефоном, фамилией (хотя в этом случае ещё и отсутствие лейбла не сыграло на пользу, сейчас непонятно, про что вообще поле) и электронной почтой

<img width="435" alt="screenshot" src="https://user-images.githubusercontent.com/26881016/127912232-ffb92a74-1e62-4aae-8314-624361e54fe0.png">

2021-08-02 19:19 UTC, avdoshenkov commented on .stylelintrc.json
> +  "ignoreFiles": ["build/*"]
Кажется тесты упали из-за этой строки, надо поправить

2021-08-02 19:19 UTC, avdoshenkov commented on src/index.ts
> +  // render(root, createCurrentPage());
Комментарий можно смело удалять, чтобы не замусоривать кодовую базу для дальнейшего чтения

2021-08-02 19:19 UTC, avdoshenkov commented on src/modules/form/Form.ts
> +    Object.entries(stateComponents).forEach(function (compState) {
Чтобы не вводить дополнительную переменную можно использовать метод `reduce` вместо `forEach`. 

Также для большей читаемости вместо переменной `compState` можно сделать [деструктуризацию массива](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment), сразу задав переменные, например, `key` и `value`. Тогда будет более понятно, что они значат по смыслу, вместо «неопределённых» элементов массива

2021-08-02 19:19 UTC, avdoshenkov commented on src/modules/form/Form.ts
> +    Object.entries(stateComponents).forEach(function (compState) {
Здесь также можно использовать `reduce`

2021-08-02 19:19 UTC, avdoshenkov commented on src/modules/form/components/input/input.tmpl.ts
> +  isPlaceholder: boolean,
По хорошему у каждого инпута должен быть свой лейбл. Это и с точки зрения семантики, и доступности будет полезно, да и пользователю удобно. Конкретно данный макет, конечно, подталкивает использовать placeholder, но всё же это не лучшее решение. Подробнее можно почитать [тут](https://www.htmhell.dev/24-a-placeholder-is-not-a-label/)

2021-08-02 19:19 UTC, avdoshenkov commented on src/modules/user/user.tmpl.ts
>          <span class="user-phone__title">Телефон</span><span class="user-phone__content">{{ phone }}</span>
Для отображения данных вида ключ-значение можно использовать специальный тег [Description List](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl)

2021-08-02 19:19 UTC, avdoshenkov commented on utils/HTTPTransport.ts
> +      const isGet = method === METHODS.GET;
Предлагаю избавиться от флажка `isGet` в общей функции `request` и перенести эту логику в тело метода `get`, т.к. она не нужна для всех остальных методов

2021-08-02 19:19 UTC, avdoshenkov commented on utils/HTTPTransport.ts
> +    if (typeof data !== "object") {
Здесь ещё нужно уточнить про `null`, иначе может быть [неожиданный](https://learn.javascript.ru/types#type-typeof) результат

2021-08-03 14:24 UTC, Tengy83 commented on src/modules/form/components/input/input.tmpl.ts
> +  isPlaceholder: boolean,
Добавил лейбл, на данный момент выводится там, где он действительно нужен(в больших формах)

2021-08-03 14:31 UTC, Tengy83 commented on utils/HTTPTransport.ts
> +      const isGet = method === METHODS.GET;
функция request общая и универсальная, и может быть вызвана на прямую, например в функции fetchWithRetry и соответственно isGet необходим в ней

2021-08-03 20:15 UTC, avdoshenkov commented on utils/HTTPTransport.ts
> +      const isGet = method === METHODS.GET;
Она действительно универсальная, но для того, чтобы в реализованных на её основе методах не дублировать кодовую базу. А если нужно использовать запрос в `fetchWithRetry`, то тогда надо использовать метод `get`, а не `request`

2021-08-03 20:40 UTC, avdoshenkov requested changes
Осталось для тестов поправить и регулярки, остальные вопросы исправлены хорошо 👍

Регулярки нужно проверить для почты (вроде адрес валидный, а форме не нравится), телефона (добавил лишних цифр — номер вся ещё валиден, хотя не должен) на странице профиля, и пароля странице логина (например, ввёл 123Test., но поле всё равно остаётся невалидным со всеми сообщениями об ошибках)

<img width="384" alt="Profile" src="https://user-images.githubusercontent.com/26881016/128082956-41371579-5296-49cc-8a2c-4d3120232e98.png">

<img width="396" alt="Sign in" src="https://user-images.githubusercontent.com/26881016/128083025-bac2e865-58ae-407c-8f2c-d1d1a4695523.png">

2021-08-03 20:40 UTC, avdoshenkov commented on .stylelintrc.json
> -  "ignoreFiles": ["build/*"]
Нет-нет, удалять не нужно, нужно скорректировать маску, чтобы не проверялись файлы из продакшн-сборки. Вот [здесь](https://github.com/Tengy83/middle.messenger.praktikum.yandex/pull/2/checks?check_run_id=3232814793#step:12:4) в логе теста указано, что ошибка возникает в `css` файлах из директории `dist`, а проверяться должны только исходники

2021-08-04 09:30 UTC, Tengy83 commented on .stylelintrc.json
> -  "ignoreFiles": ["build/*"]
По поводу проверки пароля: там в подсказках написано, что необходим еще спец символ, так что "123Test" и не должен проходить надо как минимум 123Tes#

2021-08-04 09:46 UTC, avdoshenkov approved these changes
👍

2021-08-04 09:48 UTC, avdoshenkov commented on .stylelintrc.json
> -  "ignoreFiles": ["build/*"]
Это да, я с точкой делал: `123Test.`. Но вот как раз было бы полезно в сообщении об ошибке написать, какие именно знаки ожидается увидеть среди спецсимволов

2021-09-01 13:26 UTC, bhoodream commented
Привет, ты забыл слить ПР 2-ого спринта и не создал ветку/ПР для 3-го.

Я возвращаю тебе работу на переделку, нужно:
- убрать правки 3 спринта из этого ПРа;
- слить его в мастер
- ответвиться от мастера для 3 спринта
- внести туда все правки по 3 спринту
- открыть ПР из ветки 3 спринта
- сдать работу на проверку

2021-09-02 18:33 UTC, merged