Sprint 3
Tengy83/middle.messenger.praktikum.yandex pull request #3
Opened 2021-09-02 18:35 UTC by Tengy83

2021-09-06 14:48 UTC, bhoodream requested changes
Отличная работа! Приношу извинения, что затянул с проверкой, к сожалению, не могу никак найти подходящего времени. Думаю, надо еще немного поработать над проектом. Поцеплялся по коду и столкнулся со следующими проблемами:
- [ ] не надо делать валидацию пароля на авторизации, потому что пользователь вводит свой пароль, а не создает новый. Мне пришлось запускать проект другого студента чтобы залогиниться :)
- [ ] так и не понял как работает поиск чатов/пользователей, похоже что не работает...
- [ ] удаление пользователя из чата происходит по клику многоточия, чего совсем не ожидаешь. Также это происходит настолько молча, что по началу вообще не понимаешь что случилось...
- [ ] при редактировании данных пользователя при клике по кнопке "редактировать" ничего не происходит, хотя данные сохраняются. Нужен какой то редирект или хотя бы уведомление
- [ ] странно что название папок в модулях с маленькой буквы, а название самих модулей с большой, типа `editPassword/EditPassword.ts`. Мне кажется не стоит заниматься такими играми с регистром, учитывая особенности разных операционных систем...
- [ ] не перекидывает со страницы логина на мессенджер когда пользователь уже залогинен, нажимаешь кнопку "войти" а ничего не происходит (в консоль валится ошибка что пользователь уже залогинен)
- [ ] команда `start` запускает парсель в дев режиме, хотя должна просто стартовать сервер на ноде. Не понятно зачем в продакшн среде хот релоад и все остальные плюшки дев режима...

2021-09-06 14:48 UTC, bhoodream commented on src/index.ts
> +const router = new Router("#root");
Тут можно использовать `ROOT_CONTAINER_ID`, который у тебя в константах.

2021-09-06 14:48 UTC, bhoodream commented on src/index.ts
> +  .use(URL_LINKS["home"], HomePage)
Обращение к полю объекта принято делать через дот нотацию, такого вида: `URL_LINKS.home`

2021-09-06 14:48 UTC, bhoodream commented on src/modules/editUser/EditUser.ts
> +        console.log(result.response);
логи не стоит оставлять по коду, потому что они засоряют консоль и кодовую базу

2021-09-06 14:48 UTC, bhoodream commented on src/modules/header/header.tmpl.ts
> +    </header>`;
Похоже лишний закрывающий тэг `</header>`... Либо наоборот, не хватает открывающего `<header>` :)

2021-09-06 14:48 UTC, bhoodream commented on src/modules/users/Users.ts
> +    // const usersList = new UsersList({ state: this.state.userList });
Хранить закомментированный код не стоит - засоряет кодовую базу. Пользуясь гитом, ты всегда можешь получить доступ к старым версиям любого нужного тебе файла.

2021-09-06 14:48 UTC, bhoodream commented on src/modules/users/Users.ts
> +  onClick(event: Event) {
Такой способ обрабатывать событие выглядит не совсем правильным. Было бы правильно именно здесь определять что за событие произошло, и уже в зависимости от этого вызывать тот или иной метод.

2021-09-06 14:48 UTC, bhoodream commented on src/modules/users/users.scss
> +        background: url(../../../static/img/search_icon.svg) no-repeat center;
Мне кажется не стоит из `scss` напрямую ходить в папку статик, которая даже исходниками не является, так как находится выше папки `src`. Правильно бы было либо, раздавать статику прямо из экспресса/nginx и использовать здесь изображения как `url('/img/search_icon.svg')`, либо хранить изображения локально в этом модуле, и использовать их как `url('./img/search_icon.svg')`.

2021-09-06 14:48 UTC, bhoodream commented on utils/Router.ts
> +    window.onpopstate = ((event) => {
Если я не ошибаюсь, стрелочные функции не имеют собственного `this`, поэтому по идее здесь бинды излишни https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Functions/Arrow_functions

2021-09-06 14:48 UTC, bhoodream commented on utils/Router.ts
> +  } // переход назад по истории браузера
эти комментарии излишни, так как то о чем они говорят и так очевидно. Не стоит хранить комментарии, которые не нужны - мусор для кодовой базы.

2021-09-06 14:48 UTC, bhoodream commented on utils/utils.ts
> +  const reg = new RegExp(`[${chars}]`, "gi");
кажется это перебор для функции `trim`, правильнее было бы вынести это в отдельную функцию типа `replace`

2021-09-07 19:22 UTC, Tengy83 commented on src/modules/users/Users.ts
> +  onClick(event: Event) {
Именно в этом блоке и определяется событие, см. выше строка 19 - listeners: ["click"], это список событий в этом компоненте, просто для универсальности он обрабатывается в DomListener.ts каждый модуль его наследует

2021-09-08 03:37 UTC, bhoodream commented on src/modules/users/Users.ts
> +  onClick(event: Event) {
Речь была о том, что щас код выглядит так будто ты на каждый онклик вызываешь все перечисленные методы, и только потом, заглянув в эти методы понимаешь что каждый метод проверяет ивент, и если ивент не на том таргете, то ничего не происходит. Вот тут вопрос, зачем вызывать метод чтобы он ничего не сделал.

Я говорил о том, что правильнее здесь развести выполнение методов. Я когда вызываю `createChat` по названию вижу, что этот метод создает чат, в твоем же случае он ждет ивент, который сам и проверяет и вдруг вообще ничего не делает, якобы не тот ивент, хотя название метода ничего об этих проверках не говорит. Твои методы чересчур умные и этот ум им не нужен.

Это равносильно в ридаксе в обработчике экшена вызывать все экшены какие есть, а уже внутри экшенов проверять тот ли тип экшена был передан. Но в ридаксе делается не так, там заводится свитч, который уже определяет какой экшен вызвать.

Вот тебе пример, как бы твой онклик выглядел адекватно:
```
onClick(event) {
    event.preventDefault();
    
    let isCreateChat = event.target.classList.contains("new_chat_link");
    // other checks...
  
    switch(true) {
      case isCreateChat:
        return this.createChat();
      // other cases...
      default:
        // handle unknown case
    }
  }
```

2021-09-08 10:16 UTC, Tengy83 commented on src/modules/users/users.scss
> +        background: url(../../../static/img/search_icon.svg) no-repeat center;
в этом спринте используется parcel, он при сборке в scss меняет сам адреса картинок и переносит их в dist. В следующем спринте при смене parcel на webpack я поменяю линки

2021-09-08 10:54 UTC, Tengy83 commented on utils/utils.ts
> +  const reg = new RegExp(`[${chars}]`, "gi");
Данная функция взята из рекомендованных решений Яндекс.практикума один в один и не думаю, что ее нужно изменять

2021-09-08 11:23 UTC, bhoodream commented on utils/utils.ts
> +  const reg = new RegExp(`[${chars}]`, "gi");
и на старуху бывает проруха

2021-11-25 22:59 UTC, merged